import asyncio
import unittest

from core.agents.models import Agent
from core.llm.models import ModelConfig
from core.runtime.workflow_runtime import workflow_runtime
from core.workflows.message_models import Message
from core.workflows.models import (
    Workflow,
    WorkflowEdge,
    WorkflowGraph,
    WorkflowNode,
)
from db.manager import agent_repo, message_repo, workflow_repo


class TestPhase2Gaps(unittest.TestCase):

    def setUp(self):
        self.model_config = ModelConfig(provider="mock", name="test-model")

    def test_message_session_db_migration(self):
        # Create a test message with a session_id
        session_id = "test-session-123"
        msg = Message(run_id="test-run-999",
                      session_id=session_id,
                      from_node="user",
                      content="Hello memory test!")

        created = message_repo.create(msg)
        self.assertEqual(created.session_id, session_id)

        # Retrieve by session ID
        fetched = message_repo.list_by_session(session_id)
        self.assertTrue(len(fetched) > 0)
        self.assertEqual(fetched[0].content, "Hello memory test!")
        self.assertEqual(fetched[0].session_id, session_id)

    def test_guardrails_blocking(self):

        async def run_guardrail_test():
            # Create agent with guardrails
            agent = Agent(
                name="Security Guard",
                role="Researcher",
                system_prompt="You are a researcher.",
                model=self.model_config,
                guardrails={"block_keywords": ["secret", "analysis"]},
                tools=[],
            )
            agent = agent_repo.create(agent)

            nodes = [
                WorkflowNode(id="n1", type="agent", ref=agent.id),
                WorkflowNode(id="n2", type="end"),
            ]
            edges = [WorkflowEdge(source="n1", target="n2")]
            wf = Workflow(
                name="Guardrails Test Workflow",
                graph=WorkflowGraph(nodes=nodes, edges=edges),
                entry_point="n1",
            )
            wf = workflow_repo.create(wf)

            # 1. Test Input Guardrail Trigger
            res_input = await workflow_runtime.execute(
                wf, "Tell me a secret key.", session_id="test-session-guard")
            self.assertIn("blocked by safety guardrails", res_input["output"])
            self.assertIn("Input contains blocked term", res_input["output"])

            # 2. Test Output Guardrail Trigger ('analysis' will be generated by the mock researcher response but not in prompt)
            res_output = await workflow_runtime.execute(
                wf, "Tell me about cars.", session_id="test-session-guard")
            self.assertIn("blocked by safety guardrails", res_output["output"])
            self.assertIn("Output contains restricted term",
                          res_output["output"])

            # Clean up
            agent_repo.delete(agent.id)
            workflow_repo.delete(wf.id)

        asyncio.run(run_guardrail_test())

    def test_conversational_memory(self):

        async def run_memory_test():
            # Create agent with memory enabled
            agent = Agent(
                name="Memory Keeper",
                role="Assistant",
                system_prompt="You are a memory testing assistant.",
                model=self.model_config,
                memory_config={"type": "buffer"},
                tools=[],
            )
            agent = agent_repo.create(agent)

            nodes = [
                WorkflowNode(id="n1", type="agent", ref=agent.id),
                WorkflowNode(id="n2", type="end"),
            ]
            edges = [WorkflowEdge(source="n1", target="n2")]
            wf = Workflow(
                name="Memory Test Workflow",
                graph=WorkflowGraph(nodes=nodes, edges=edges),
                entry_point="n1",
            )
            wf = workflow_repo.create(wf)

            session_id = "test-conversation-session-456"

            # Execute first turn
            res1 = await workflow_runtime.execute(wf,
                                                  "My favorite color is Blue.",
                                                  session_id=session_id)
            self.assertEqual(res1["status"], "completed")

            # Execute second turn
            res2 = await workflow_runtime.execute(wf,
                                                  "What is my favorite color?",
                                                  session_id=session_id)
            self.assertEqual(res2["status"], "completed")

            # Fetch database messages for this session
            messages = message_repo.list_by_session(session_id)
            # The database should have recorded multiple messages for this session
            self.assertTrue(len(messages) >= 2)

            # Clean up
            agent_repo.delete(agent.id)
            workflow_repo.delete(wf.id)

        asyncio.run(run_memory_test())
